# ===== Server Configuration =====
server.port=8080

# ===== Application Info =====
spring.application.name=insurance-portal-backend

# ===== PostgreSQL Database Configuration =====
# TODO: Update username, password, and database name before running
spring.datasource.url=jdbc:postgresql://ep-orange-queen-ai2qcg4n-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_YH1hAIxnrzK6&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
# IMPORTANT: Do NOT put your real password here — this file is committed to Git!
# Create src/main/resources/application-local.properties (gitignored) with:
#   spring.datasource.password=your_actual_passwßord
# PGUSER=neondb_owner
# PGPASSWORD=npg_YH1hAIxnrzK6
spring.datasource.password=npg_YH1hAIxnrzK6
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate Configuration =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT Configuration =====
# Secret key (Base64-encoded, min 256-bit for HS256)
# TODO: Replace with a strong secret in production (use env variable)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
# Refresh token expiry — 7 days
app.jwt.refresh-expiration-ms=604800000

# ===== Logging =====
logging.level.com.insuranceportal=DEBUG
logging.level.org.springframework.security=DEBUG

#======swagger changes
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=Insurance Portal API
springdoc.info.version=1.0.0
springdoc.info.description=REST API for the Insurance Portal backend

#====== Cloudinary Configuration =======
cloudinary.cloud-name=your_cloud_name
cloudinary.api-key=your_api_key
cloudinary.api-secret=your_api_secret
